-- mysql-a 初始化：两个业务库，带中文注释的表结构
-- SET NAMES 必须有：否则 mysql 客户端按 latin1 读本文件，中文会被双重编码
SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS db_shop DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS db_log DEFAULT CHARACTER SET utf8mb4;

USE db_shop;
CREATE TABLE customer (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  name VARCHAR(64) NOT NULL COMMENT '客户姓名',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  level TINYINT NOT NULL DEFAULT 1 COMMENT '等级 1普通 2VIP 3SVIP',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY uk_phone (phone)
) ENGINE=InnoDB COMMENT='客户表';

CREATE TABLE orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '订单号',
  customer_id BIGINT UNSIGNED NOT NULL COMMENT '客户ID',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '金额',
  status VARCHAR(16) NOT NULL DEFAULT 'created' COMMENT '状态',
  KEY idx_customer (customer_id)
) ENGINE=InnoDB COMMENT='订单表';

USE db_log;
CREATE TABLE access_log (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(255) NOT NULL COMMENT '请求路径',
  cost_ms INT NOT NULL DEFAULT 0 COMMENT '耗时(毫秒)',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='访问日志';
